### ISSUE TITLE
Add browser-wallet-manager

### ISSUE THREAD

**Issue by av-vonsbak** [alien-valley/znn.js#6]
When using the SDK in a browser environment, the developer might expect to find/store keyFiles in cookies / browser session.

This requires a lot of moving pieces which I’m not aware on how to deal with at the moment.

The cookies/session storage is just an idea. I’ve never actually done anything remotely similar to this before
If anyone has any thoughts on how this works/what to expect, please hit me up
E.G: a project/medium article that simulates a directory structure/file system in the browser-session/cookies will be of amazing help 🙏🏻

**Comment by ghost** [comment]
For our extension wallet it would be the easiest to simply return the wallet as JSON object and leave it up to the SDK user how to store the wallet in his context. I assume that this is anyway not needed directly by a dapp and only by wallet providers...

**Comment by av-vonsbak** [comment]
You're right. This feature was intended to be used only by the wallet providers. It can be integrated in the SDK if multiple providers want to manage multiple keyStores at the same time.

This does not restrict the ability to own the JSON file; it just tries to take care of saving it for you.

I guess for node it made **more sense** to be inside the SDK since it should be compliant w/ the go-zenon, Syrius and znn-cli as well (since the location is shared). The browser is a **brave new world**, and the fact that the JSON is not shared between providers renders this useless.
